### PR TITLE
Add DetailedApiRequestError and mapping from JSON

### LINKED ISSUE #3: Error handling?
I want my app to properly respond to errors returned by my API. This means that I need to get access to the JSON returned. Eg:

``` json
{
  "error": {
    "code": 404,
    "message": "The email you provided was invalid",
    "errors": [ {"reason": "InvalidEmail"} ]
  }
}
```

Now, from what I could see, the generated client library throws a `DetailedApiRequestError` in case of a server error. Unfortunately, this exposes nothing apart from the `message`.
Right now there is no proper way to get the error reasons from the json.

It would be great if the `DetailedApiRequestError` could also contain the list of errors retained (as specified in the [Google JSON style guide](http://google-styleguide.googlecode.com/svn/trunk/jsoncstyleguide.xml?showone=error#error.errors)).

### PR DESCRIPTION
**Pull request by enyo**
This commit also adds the necessary tests for this functionality.

Closes #3 

Basically, this is the client side of the functionality introduced here: https://github.com/dart-lang/rpc/pull/69

### CODE REVIEW

**Comment by enyo** [comment]
@wibling if anything needs changing I'll do it right away. Cheers

**Comment by wibling** [comment]
LGTM

**Comment by wibling** [comment]
All looked good. I have merged and published a new package.

**Comment by kevmoo** [comment]
Thanks, @enyo! :metal:

**Comment by enyo** [comment]
No problem. You take some, you give some, right? ;)

**Pull request merged**
